#Snakemake configuration file

#project directory this needs to be changed
proj_dir: /project2/xinhe/alan/Cancer/sampleData/

# REF GENOME FILE (must contain .fasta, .fai, .dic)
REF_GENOME_DIR: /project2/xinhe/alan/Cancer/refGenome/GRCh37Lite.fasta
SITES_VAR: /project2/xinhe/alan/Cancer/sites_variation/

# Number of clonal clusters for Titan
CLONAL_CLUSTERS: 3

# GC content and mappability files for the reference genome
GC_FILE: /project2/xinhe/alan/Cancer/refGenome/gc_hg19.wig 
MAP_FILE: /project2/xinhe/alan/Cancer/refGenome/map_hg19.wig

# Sample names for somatic mutations
tumor_sample_name: "tumor"
normal_sample_name: "normal"

